import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    environment: 'jsdom',
    include: [
      'packages/contracts/src/phase3*.test.ts',
      'apps/api/src/**/*commercial*.test.ts',
      'apps/api/src/**/*phase3*.test.ts',
      'apps/api/src/plans-api.test.ts',
      'apps/api/src/memberships-api.test.ts',
      'apps/api/src/packages-api.test.ts',
      'apps/api/src/makeup-credits-api.test.ts',
      'apps/api/src/fixed-court-agreements-api.test.ts',
      'apps/api/src/credit-adjustments-api.test.ts',
      'apps/api/src/commercial-authorization.test.ts',
      'apps/api/src/commercial-api-lists.test.ts',
      'apps/api/src/reports-api.test.ts',
      'apps/api/src/services/plans.test.ts',
      'apps/api/src/services/memberships.test.ts',
      'apps/api/src/services/packages.test.ts',
      'apps/api/src/services/entitlements.test.ts',
      'apps/api/src/services/entitlement-priority.test.ts',
      'apps/api/src/services/reservation-entitlements.test.ts',
      'apps/api/src/services/class-entitlements.test.ts',
      'apps/api/src/services/makeup-credits.test.ts',
      'apps/api/src/services/fixed-court-agreements.test.ts',
      'apps/api/src/services/customer-commercial-balance.test.ts',
      'apps/api/src/services/commercial-evaluation.test.ts',
      'apps/api/src/services/commercial-reporting.test.ts',
      'apps/api/src/services/commercial-activity-events.test.ts',
      'apps/api/src/services/commercial-reconciliation.test.ts',
      'apps/api/src/services/customer-portal/commercial.test.ts',
      'apps/api/src/migrations/phase3.test.ts',
      'apps/api/src/journeys/commercial.journey.test.ts',
      'apps/api/src/journeys/phase3-regression.journey.test.ts',
      'apps/web/src/screens/commercial-overview.test.ts',
      'apps/web/src/screens/memberships.test.ts',
    ],
    exclude: ['**/integration/**', '**/node_modules/**'],
  },
});
