import { t } from '../i18n.js';
import { toast } from '../ui/feedback.js';
import { formData, setBusy, showFormError } from '../ui/forms.js';
import { closeModal, openModal } from '../ui/modal.js';
import { shell } from '../ui/shell.js';
import { app, escapeText, renderRoute, request } from './runtime.js';

type StaffMember = { userId: string; name: string; email: string; role: string; active: boolean };
export async function staff() {
  const data = await request<StaffMember[]>('/staff');
  await shell(async () => { setTimeout(wireStaff, 0); return `<div class="toolbar"><h2>${t('staff.title')}</h2><button class="button primary" id="add-staff">${t('staff.add')}</button></div><article class="card table-wrap"><table><thead><tr><th>${t('common.name')}</th><th>${t('common.email')}</th><th>${t('staff.role')}</th><th>${t('common.status')}</th><th>${t('common.actions')}</th></tr></thead><tbody>${data.map((item) => `<tr><td>${escapeText(item.name)}</td><td>${escapeText(item.email)}</td><td>${escapeText(item.role)}</td><td>${item.active ? t('common.active') : t('common.inactive')}</td><td><button class="button small" data-toggle-staff="${escapeText(item.userId)}" data-active="${item.active}">${item.active ? t('common.deactivate') : t('common.activate')}</button><button class="button small" data-reset-staff="${escapeText(item.userId)}">${t('staff.resetPassword')}</button></td></tr>`).join('')}</tbody></table></article>`; });
}
function form(title: string, reset = false) { return `<form id="staff-form" class="form-grid">${reset ? '' : `<label>${t('common.name')}<input name="name" required></label><label>${t('common.email')}<input name="email" type="email" required></label><label>${t('staff.role')}<select name="role"><option>STAFF</option><option>COACH</option><option>OWNER</option></select></label>`}<label>${t('staff.password')}<input name="password" type="password" required></label><p class="form-error" role="alert"></p><div class="form-actions full"><button type="button" class="button" data-close>${t('common.cancel')}</button><button class="button primary">${title}</button></div></form>`; }
function wireStaff() { app.querySelector('#add-staff')?.addEventListener('click', () => openStaffModal()); app.querySelectorAll<HTMLElement>('[data-toggle-staff]').forEach((button) => button.addEventListener('click', async () => { if (button.dataset.active === 'true' && !window.confirm(t('staff.confirmDeactivate'))) return; await request(`/staff/${button.dataset.toggleStaff}`, { method: 'PATCH', body: JSON.stringify({ active: button.dataset.active !== 'true' }) }); await renderRoute(); })); app.querySelectorAll<HTMLElement>('[data-reset-staff]').forEach((button) => button.addEventListener('click', () => openStaffModal(String(button.dataset.resetStaff), true))); }
function openStaffModal(userId?: string, reset = false) { openModal(reset ? t('staff.resetPassword') : t('staff.add'), form(reset ? t('staff.resetPassword') : t('common.create'), reset)); const element = app.querySelector<HTMLFormElement>('#staff-form'); element?.querySelector('[data-close]')?.addEventListener('click', closeModal); element?.addEventListener('submit', async (event) => { event.preventDefault(); setBusy(element, true); try { const values = formData(element); await request(userId ? `/staff/${userId}/reset-password` : '/staff', { method: userId ? 'POST' : 'POST', body: JSON.stringify(userId ? { password: values.password } : values) }); closeModal(); toast(t('common.saveChanges')); await renderRoute(); } catch (error) { showFormError(element, error); setBusy(element, false); } }); }
