import { randomUUID } from 'node:crypto';
import { collection, CourtInputSchema, CustomerInputSchema, ExpenseInputSchema, LoginInputSchema, ok, PaginationSchema, PaymentInputSchema, ReservationInputSchema, RequestInputSchema } from '@court-manager/contracts';
import type { AuthContext } from '@court-manager/contracts';
import { Hono } from 'hono';
import type { Context } from 'hono';
import { cors } from 'hono/cors';
import { z, type ZodType } from 'zod';
import type { Repository } from './db.js';
import { AppError } from './errors.js';
import { buildServices } from './services/index.js';

type Variables={auth:AuthContext;requestId:string};
type AppContext=Context<{Variables:Variables}>;
const csv=(rows:Record<string,unknown>[])=>{if(!rows.length)return '';const headers=Object.keys(rows[0]??{});const quote=(v:unknown)=>`"${String(v??'').replaceAll('"','""')}"`;return [headers.join(','),...rows.map(row=>headers.map(h=>quote(row[h])).join(','))].join('\n');};
const body=async<T>(c:{req:{json:()=>Promise<unknown>}},schema:ZodType<T>)=>{const parsed=schema.safeParse(await c.req.json().catch(()=>null));if(!parsed.success)throw new AppError('VALIDATION_ERROR','Request validation failed.',parsed.error.flatten().fieldErrors);return parsed.data;};

export const createApp=(repo:Repository)=>{const services=buildServices(repo);const app=new Hono<{Variables:Variables}>();
  const publicRequests=new Map<string,{started:number;count:number}>();
  app.onError((error,c)=>{const requestId=c.get('requestId')??randomUUID();if(error instanceof AppError)return c.json({error:{code:error.code,message:error.message,details:error.details,requestId}},error.status as 400);console.error(JSON.stringify({requestId,error:error.message,route:c.req.path}));return c.json({error:{code:'INTERNAL_ERROR',message:'An unexpected error occurred.',details:{},requestId}},500);});
  app.use('*',async(c,next)=>{const requestId=randomUUID();c.set('requestId',requestId);const started=Date.now();await next();console.info(JSON.stringify({requestId,route:c.req.path,method:c.req.method,status:c.res.status,duration:Date.now()-started,organizationId:c.get('auth')?.organizationId,userId:c.get('auth')?.userId}));});
  app.use('*',cors({origin:'*',allowHeaders:['Authorization','Content-Type'],allowMethods:['GET','POST','PATCH','DELETE','OPTIONS']}));
  app.use('/public/*',async(c,next)=>{if(Number(c.req.header('Content-Length')??0)>65536)throw new AppError('VALIDATION_ERROR','Request body is too large.');if(c.req.method==='POST'){const address=c.req.header('x-forwarded-for')??'local';const current=publicRequests.get(address);const timestamp=Date.now();if(!current||timestamp-current.started>60000)publicRequests.set(address,{started:timestamp,count:1});else{current.count+=1;if(current.count>30)throw new AppError('RATE_LIMITED','Too many public requests.');}}await next();});
  const auth=async(c:AppContext)=>{const header=c.req.header('Authorization');if(!header?.startsWith('Bearer '))throw new AppError('UNAUTHORIZED','Authentication required.');const context=await services.auth.authenticate(header.slice(7));c.set('auth',context);};
  const ctx=(c:AppContext)=>c.get('auth');
  const protectedRoute=async(c:AppContext,next:()=>Promise<void>)=>{await auth(c);await next();};
  app.get('/health',c=>c.json({status:'ok'}));
  app.post('/auth/login',async c=>{const input=await body(c,LoginInputSchema);return c.json(ok(await services.auth.login(input.email,input.password)));});
  app.post('/auth/logout',async c=>{await auth(c);const token=c.req.header('Authorization')?.slice(7);if(token)await services.auth.logout(token);return c.json(ok({loggedOut:true}));});
  app.get('/public/venues/:slug',async c=>c.json(ok(await services.requests.publicVenue(c.req.param('slug')))));
  app.get('/public/venues/:slug/availability',async c=>{const query=c.req.query();const result=await services.requests.publicAvailability(c.req.param('slug'),query.courtId??'',query.date??'',Number(query.durationMinutes??30));return c.json(ok(result));});
  app.post('/public/venues/:slug/requests',async c=>{const input=await body(c,RequestInputSchema);return c.json(ok(await services.requests.createPublic(c.req.param('slug'),input)),201);});
  app.use('/organization/*',protectedRoute);app.use('/courts/*',protectedRoute);app.use('/customers/*',protectedRoute);app.use('/reservations/*',protectedRoute);app.use('/schedule',protectedRoute);app.use('/availability',protectedRoute);app.use('/requests/*',protectedRoute);app.use('/payments/*',protectedRoute);app.use('/expenses/*',protectedRoute);app.use('/blocks/*',protectedRoute);app.use('/classes/*',protectedRoute);app.use('/dashboard',protectedRoute);app.use('/reports/*',protectedRoute);app.use('/exports/*',protectedRoute);
  app.get('/organization',async c=>c.json(ok(await services.organizations.get(ctx(c)))));
  app.patch('/organization',async c=>c.json(ok(await services.organizations.update(ctx(c),await body(c,z.record(z.unknown()))))));
  app.get('/courts',async c=>c.json(collection(await services.courts.list(ctx(c)))));
  app.post('/courts',async c=>c.json(ok(await services.courts.create(ctx(c),await body(c,CourtInputSchema))),201));
  app.get('/courts/:id',async c=>c.json(ok(await services.courts.get(ctx(c),c.req.param('id')))));
  app.patch('/courts/:id',async c=>c.json(ok(await services.courts.update(ctx(c),c.req.param('id'),await body(c,CourtInputSchema.partial())))));
  app.post('/courts/:id/archive',async c=>c.json(ok(await services.courts.archive(ctx(c),c.req.param('id')))));
  app.post('/courts/:id/restore',async c=>c.json(ok(await services.courts.restore(ctx(c),c.req.param('id')))));
  app.get('/customers',async c=>{const q=c.req.query(),p=PaginationSchema.parse(q);const data=await services.customers.list(ctx(c),q.search,q.archived==='true');return c.json(collection(data.slice(0,p.limit),null));});
  app.post('/customers',async c=>c.json(ok(await services.customers.create(ctx(c),await body(c,CustomerInputSchema))),201));
  app.get('/customers/:id',async c=>c.json(ok(await services.customers.get(ctx(c),c.req.param('id')))));
  app.patch('/customers/:id',async c=>c.json(ok(await services.customers.update(ctx(c),c.req.param('id'),await body(c,CustomerInputSchema.partial())))));
  app.post('/customers/:id/archive',async c=>c.json(ok(await services.customers.archive(ctx(c),c.req.param('id')))));
  app.get('/customers/duplicates',async c=>c.json(ok(await services.customers.duplicates(ctx(c),c.req.query()))));
  app.get('/reservations',async c=>{const q=c.req.query(),p=PaginationSchema.parse(q);return c.json(collection((await services.reservations.list(ctx(c),q)).slice(0,p.limit),null));});
  app.post('/reservations',async c=>c.json(ok(await services.reservations.create(ctx(c),await body(c,ReservationInputSchema))),201));
  app.post('/reservations/recurring',async c=>c.json(ok(await services.reservations.recurring(ctx(c),await body(c,z.record(z.unknown())))),201));
  app.get('/reservations/:id',async c=>c.json(ok(await services.reservations.detail(ctx(c),c.req.param('id')))));
  app.patch('/reservations/:id',async c=>c.json(ok(await services.reservations.update(ctx(c),c.req.param('id'),await body(c,ReservationInputSchema.partial())))));
  app.post('/reservations/:id/complete',async c=>c.json(ok(await services.reservations.transition(ctx(c),c.req.param('id'),'COMPLETED'))));
  app.post('/reservations/:id/cancel',async c=>c.json(ok(await services.reservations.transition(ctx(c),c.req.param('id'),'CANCELLED'))));
  app.post('/reservations/:id/no-show',async c=>c.json(ok(await services.reservations.transition(ctx(c),c.req.param('id'),'NO_SHOW'))));
  app.get('/schedule',async c=>{const q=c.req.query();if(q.from&&q.to&&new Date(q.to).getTime()-new Date(q.from).getTime()>7*86400000)throw new AppError('VALIDATION_ERROR','Schedule range cannot exceed seven days.');const date=q.date??q.from??new Date().toISOString().slice(0,10);const courts=await services.courts.list(ctx(c));const reservations=await services.reservations.list(ctx(c),{date});const blocks=await services.blocks.list(ctx(c));return c.json(ok({date,courts,items:[...reservations,...blocks]}));});
  app.get('/availability',async c=>{const q=c.req.query();const court=await services.courts.get(ctx(c),q.courtId??'');return c.json(ok({available:await services.schedule.availability(ctx(c),court as Parameters<typeof services.schedule.availability>[1],q.date??'',Number(q.durationMinutes??30))}));});
  app.get('/blocks',async c=>c.json(collection(await services.blocks.list(ctx(c)))));
  app.post('/blocks',async c=>c.json(ok(await services.blocks.create(ctx(c),await body(c,z.record(z.unknown())))),201));
  app.post('/blocks/:id/cancel',async c=>c.json(ok(await services.blocks.cancel(ctx(c),c.req.param('id')))));
  app.get('/requests',async c=>c.json(collection(await services.requests.list(ctx(c)))));
  app.get('/requests/:id',async c=>{const request=(await services.requests.list(ctx(c)) as Record<string,unknown>[]).find(item=>String(item['requestId'])===c.req.param('id'));if(!request)throw new AppError('NOT_FOUND','Request was not found.');return c.json(ok(request));});
  app.post('/requests/:id/confirm',async c=>{const input=await body(c,z.object({customerId:z.string().optional()}));return c.json(ok(await services.requests.confirm(ctx(c),c.req.param('id'),input.customerId)));});
  app.post('/requests/:id/reject',async c=>{const input=await body(c,z.object({reason:z.string().optional()}));return c.json(ok(await services.requests.reject(ctx(c),c.req.param('id'),input.reason)));});
  app.get('/payments',async c=>c.json(collection(await services.payments.list(ctx(c)))));
  app.post('/payments',async c=>c.json(ok(await services.payments.create(ctx(c),await body(c,PaymentInputSchema))),201));
  app.delete('/payments/:id',async c=>{await services.payments.remove(ctx(c),c.req.param('id'));return c.json(ok({deleted:true}));});
  app.get('/expenses',async c=>c.json(collection(await services.expenses.list(ctx(c)))));
  app.post('/expenses',async c=>c.json(ok(await services.expenses.create(ctx(c),await body(c,ExpenseInputSchema))),201));
  app.get('/classes',async c=>c.json(collection(await services.classes.list(ctx(c)))));
  app.post('/classes',async c=>c.json(ok(await services.classes.create(ctx(c),await body(c,z.record(z.unknown())))),201));
  app.post('/classes/:id/enroll',async c=>{const input=await body(c,z.object({customerId:z.string()}));return c.json(ok(await services.classes.enroll(ctx(c),c.req.param('id'),input.customerId)),201);});
  app.post('/classes/attendance',async c=>c.json(ok(await services.classes.attendance(ctx(c),await body(c,z.record(z.unknown())))),201));
  app.get('/dashboard',async c=>{const q=c.req.query(),date=q.date??new Date().toISOString().slice(0,10),reservations=await services.reservations.list(ctx(c),{date}),requests=await services.requests.list(ctx(c)),payments=await services.payments.list(ctx(c));const expected=reservations.reduce((n,r)=>n+Number(r.expectedAmount),0),paid=payments.filter(p=>reservations.some(r=>r.reservationId===p.reservationId)).reduce((n,p)=>n+Number(p.amount),0);return c.json(ok({date,reservationsToday:reservations.length,pendingRequests:requests.filter(r=>r.status==='REQUESTED').length,expectedRevenue:expected,recordedPayments:paid,outstanding:Math.max(0,expected-paid),upcoming:reservations}));});
  app.get('/reports/summary',async c=>{const reservations=await services.reservations.list(ctx(c),c.req.query()),payments=await services.payments.list(ctx(c));return c.json(ok({reservationCount:reservations.length,expectedRevenue:reservations.reduce((n,r)=>n+Number(r.expectedAmount),0),recordedPayments:payments.reduce((n,p)=>n+Number(p.amount),0),sources:Object.fromEntries(['PUBLIC_REQUEST','WHATSAPP','PHONE','WALK_IN','STAFF','OTHER'].map(s=>[s,reservations.filter(r=>r.source===s).length]))}));});
  for(const entity of ['customers','reservations','payments','expenses'] as const)app.get(`/exports/${entity}`,async c=>{const data=entity==='customers'?await services.customers.list(ctx(c)):entity==='reservations'?await services.reservations.list(ctx(c),c.req.query()):entity==='payments'?await services.payments.list(ctx(c)):await services.expenses.list(ctx(c));return new Response(csv(data as Record<string,unknown>[]),{headers:{'Content-Type':'text/csv; charset=utf-8','Content-Disposition':`attachment; filename=${entity}.csv`}});});
  return app;
};
